language: node_js
node_js: 
  - 13.6.0

install:
  - cd js_Vue & npm ci && npm i
env:
  - TEST=true 
script:
  - npm run test

os: linux
dist: bionic
arch: amd64

cache: npm
timeout: 1000
directories: 
     - .cache
     - $HOME/.npm
     - node_modules
