language: node_js
node_js: 
  - 13.6.0
  - 10
  - 9
  - 8
 
sudo: false
install:
  - cd js_Vue & npm ci && npm i
script:
  - npm run test

os: linux
dist: bionic
arch: amd64

cache:
  npm: true
  timeout: 1000
  directories: 
     - .cache
     - $HOME/.npm
     - node_modules
