language: node_js

os: linux
dist: bionic

arch: amd64

before_install:
  - npm i
  
install:
- npm ci

node_js: 
  - "v13.6.0"

cache:
  npm: true
  timeout: 1000
  directories: 
     - ".cache"
     - "$HOME/.npm"
     - "node_modules"